#!/bin/bash

rm -rf m2_repo
rm -rf target
rm -rf ~/.m2/.develocity/fingerprint-cache
rm -rf ~/.m2/.develocity/token-cache

echo "Building develocity-bamboo-plugin with dependencies from local Artifactory"

SECONDS=0
./mvnw clean package -q -Dmaven.repo.local=m2_repo -s ../settings-local.xml -Dscan.tag.LOCAL_ARTIFACTORY_DOWNLOAD
ARTIFACTORY_BUILD=$SECONDS

echo "====== Build with Artifactory complete"

rm m2_repo.tgz
tar -czf m2_repo.tgz m2_repo

rm -rf m2_repo
rm -rf target
rm -rf ~/.m2/.develocity/fingerprint-cache
rm -rf ~/.m2/.develocity/token-cache

echo "Building develocity-bamboo-plugin with dependencies from local tarball"

SECONDS=0
tar -xf m2_repo.tgz
TARBALL_EXTRACT=$SECONDS
./mvnw clean package -q -Dmaven.repo.local=m2_repo -s ../settings-local.xml -Dscan.tag.LOCAL_TARBALL_EXTRACT
TARBALL_BUILD=$SECONDS

echo "====== Build from tarball complete"

echo ""
echo "Artifactory build: $ARTIFACTORY_BUILD sec"
echo "Tarball build: $TARBALL_BUILD sec"
echo " - Extract tarball: $TARBALL_EXTRACT sec"
